import type { ThemeStyles } from "@/types/theme-styles";

export interface ThemePreset {
  name: string;
  description: string;
  styles: ThemeStyles;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: "Cinematic",
    description: "Atmosphere, tension, and narrative",
    styles: {
      primaryColor: "#c9a84c",
      secondaryColor: "#8b7332",
      accentColor: "#ffd700",
      backgroundColor: "#0d0d0d",
      surfaceColor: "#1a1708",
      textColor: "#f5f0e1",
      textMutedColor: "#8b8470",
      fontFamily: "Playfair Display",
      fontHeadingFamily: "Playfair Display",
      animationType: "fade-in",
      borderRadius: "0.5rem",
    },
  },
  {
    name: "Violence",
    description: "Intensity without apology",
    styles: {
      primaryColor: "#ff0000",
      secondaryColor: "#8b0000",
      accentColor: "#ff4444",
      backgroundColor: "#0a0000",
      surfaceColor: "#1a0505",
      textColor: "#ffffff",
      textMutedColor: "#ff8888",
      fontFamily: "Oswald",
      fontHeadingFamily: "Oswald",
      animationType: "glitch",
      borderRadius: "0",
    },
  },
  {
    name: "Groove",
    description: "Rhythm as a physical force",
    styles: {
      primaryColor: "#00ff88",
      secondaryColor: "#008844",
      accentColor: "#00ffcc",
      backgroundColor: "#050a08",
      surfaceColor: "#0a1a14",
      textColor: "#e0fff0",
      textMutedColor: "#66aa88",
      fontFamily: "Space Mono",
      fontHeadingFamily: "Orbitron",
      animationType: "pulse-glow",
      borderRadius: "0.25rem",
    },
  },
  {
    name: "Experimental",
    description: "Sound without a map",
    styles: {
      primaryColor: "#aa44ff",
      secondaryColor: "#6622aa",
      accentColor: "#dd88ff",
      backgroundColor: "#08050d",
      surfaceColor: "#140a1a",
      textColor: "#f0e0ff",
      textMutedColor: "#9966bb",
      fontFamily: "Space Grotesk",
      fontHeadingFamily: "Space Grotesk",
      animationType: "float",
      borderRadius: "1rem",
    },
  },
  {
    name: "Guitar",
    description: "Strings, dirt, and tension",
    styles: {
      primaryColor: "#b87333",
      secondaryColor: "#5a3a1e",
      accentColor: "#e09f3e",
      backgroundColor: "#0f0b08",
      surfaceColor: "#1c1510",
      textColor: "#f3ede6",
      textMutedColor: "#9c8a78",
      fontFamily: "DM Sans",
      fontHeadingFamily: "Syne",
      animationType: "fade-in",
      borderRadius: "0.75rem",
    },
  },
  {
    name: "Analog",
    description: "Warm strings, imperfect beauty",
    styles: {
      primaryColor: "#e8a87c",
      secondaryColor: "#c17850",
      accentColor: "#f4c587",
      backgroundColor: "#1a1210",
      surfaceColor: "#2a1f1a",
      textColor: "#f5ebe0",
      textMutedColor: "#a0897a",
      fontFamily: "DM Sans",
      fontHeadingFamily: "Syne",
      animationType: "fade-in",
      borderRadius: "1.5rem",
    },
  },
  {
    name: "Neon",
    description: "Synthetic light, human feeling",
    styles: {
      primaryColor: "#ff2d95",
      secondaryColor: "#b01e6a",
      accentColor: "#00f0ff",
      backgroundColor: "#0a0520",
      surfaceColor: "#150a30",
      textColor: "#f0e8ff",
      textMutedColor: "#8070aa",
      fontFamily: "Chakra Petch",
      fontHeadingFamily: "Orbitron",
      animationType: "flicker",
      borderRadius: "0.25rem",
    },
  },
  {
    name: "Dark",
    description: "Tension, silence, and depth",
    styles: {
      primaryColor: "#4b5d73",
      secondaryColor: "#2a3440",
      accentColor: "#7a8fa6",
      backgroundColor: "#05070a",
      surfaceColor: "#0b1016",
      textColor: "#d6dde6",
      textMutedColor: "#6b7785",
      fontFamily: "Libre Baskerville",
      fontHeadingFamily: "Raleway",
      animationType: "grain",
      borderRadius: "0.5rem",
    },
  },
  {
    name: "Trap",
    description: "Bold energy, golden grit",
    styles: {
      primaryColor: "#ffd700",
      secondaryColor: "#b8960c",
      accentColor: "#ffe44d",
      backgroundColor: "#0a0a0a",
      surfaceColor: "#1a1800",
      textColor: "#ffffff",
      textMutedColor: "#a09060",
      fontFamily: "Montserrat",
      fontHeadingFamily: "Archivo Black",
      animationType: "slide-up",
      borderRadius: "0.25rem",
    },
  },
  {
    name: "Melodic",
    description: "Simple motifs, deep impact",
    styles: {
      primaryColor: "#6fa3c8",
      secondaryColor: "#3a5f7a",
      accentColor: "#e3f2fd",
      backgroundColor: "#070c12",
      surfaceColor: "#0e1620",
      textColor: "#eaf2f8",
      textMutedColor: "#8aa0b3",
      fontFamily: "Raleway",
      fontHeadingFamily: "Playfair Display",
      animationType: "fade-in",
      borderRadius: "0.75rem",
    },
  },
  {
    name: "Unreleased",
    description: "Beautiful mistakes and strange grooves",
    styles: {
      primaryColor: "#c084fc",
      secondaryColor: "#8b5cf6",
      accentColor: "#f0abfc",
      backgroundColor: "#0c0618",
      surfaceColor: "#180d2e",
      textColor: "#f0e6ff",
      textMutedColor: "#9080b0",
      fontFamily: "Raleway",
      fontHeadingFamily: "Unbounded",
      animationType: "wave",
      borderRadius: "1rem",
    },
  },
  {
    name: "Noise",
    description: "When distortion becomes language",
    styles: {
      primaryColor: "#a0a8b0",
      secondaryColor: "#6a7078",
      accentColor: "#e87040",
      backgroundColor: "#0c0c0e",
      surfaceColor: "#18181c",
      textColor: "#e0e0e4",
      textMutedColor: "#707478",
      fontFamily: "JetBrains Mono",
      fontHeadingFamily: "Bebas Neue",
      animationType: "slide-left",
      borderRadius: "0",
    },
  },
];
